In [2]:
# numpy 관련
import numpy as np

In [3]:
arr = np.arange(15)
print(arr)
type(arr)
arr = arr.reshape(3,5)
print(arr)
print(arr, arr.ndim)
print()
print(arr.shape, arr.size, arr.dtype.name)
print(arr.dtype.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 2

(3, 5) 15 int32
4


In [15]:
arr = np.arange(-5, 5, 0.5)
arr = arr.reshape(4, int(arr.size/4))
arr
arr1 = arr.flatten()
arr1.ndim

1

In [18]:
# 기존의 파이썬 리스트로 array 생성
list_a = np.array([1, 2, 3])
list_b = np.array([[1, 2, 3], [4, 5, 6]])
print('list_a : {}, list_a의 type : {}'.format(list_a, type(list_a)))
print('list_b : {}, list_b의 type : {}'.format(list_b, type(list_b)))

list_a : [1 2 3], list_a의 type : <class 'numpy.ndarray'>
list_b : [[1 2 3]
 [4 5 6]], list_b의 type : <class 'numpy.ndarray'>


In [ ]:
# np.arange([start], stop, [step])
# np.array.reshape(차수, ..)
# np.ndim, np.shape, np.dtype, np.ndim, np.dtype.name