In [1]:
import numpy as np

In [3]:
print(np.random.rand(2,3), np.random.randn(2,3))

[[0.28024459 0.2529862  0.48421139]
 [0.28374827 0.63032393 0.08093332]] [[-0.30316589  1.10867484 -0.06212846]
 [-0.13815746 -0.09565756  0.93078768]]


In [4]:
# numpy 일반 함수
# np.cos, tanh(), exp()

In [7]:
# 기술 통계 함수
# count() mean() var() std() median() max main() perctile()
arr = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
               2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(arr))
print(np.percentile(arr,50)) # 2분위 수

26
5.0


In [9]:
# 난수 발생과 카운팅
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [12]:
# 데이터 순서를 바꾸는 방법
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 1 9 2 6 7 0 3 4 8]


In [18]:
# 샘플링 : choice()
np.random.choice(5,5, replace=False) # shuffle 과 같은 결과
np.random.choice(10, 3, replace=False) # 10개중 3개만 선택
np.random.choice(5, 10) # 5개 중 10개 추출 : 중복허용
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 선택확률을 다르게

array([3, 3, 3, 0, 3, 0, 3, 3, 2, 3])

In [25]:
# randint() 정수 난수 발생 np.random.randint(low, high=None, size=None)
np.random.seed(0)
np.random.randint(10, size=10) # 10 포함안함
np.random.randint(10,20, size=10)
np.random.randint(10,20, size=(3,5))

array([[15, 18, 12, 13, 19],
       [17, 15, 13, 14, 15],
       [13, 13, 17, 19, 19]])

In [32]:
x = np.arange(1, 21, 1)
print('3의 배수 :', x[(x%3)==0])
print('4로 나누면 1 :', x[(x%4)==1])
print('3로 나누면 1 :', x[((x%4)==1) & ((x%3)==0)])

3의 배수 : [ 3  6  9 12 15 18]
4로 나누면 1 : [ 1  5  9 13 17]
3로 나누면 1 : [9]
